/* global window */

(function attachConfigModule(globalScope) {
  "use strict";

  const DEFAULT_SYNC_TARGET_SOURCE_NAME = "iCloud";
  const DEFAULT_SYNC_TARGET_CALENDAR_NAME = "个人";
  const DEFAULT_REMINDER_TARGET_SOURCE_NAME = "iCloud";
  const DEFAULT_REMINDER_TARGET_LIST_NAME = "提醒";

  const config = {
    STORAGE_KEY: "time_quality_journal_v1",
    QUOTE_POOL_KEY: "time_quality_quote_pool_v1",
    QUOTE_LIBRARY_KEY: "time_quality_quote_library_v1",
    EXTERNAL_CALENDAR_SYNC_URL: "./calendar_sync.json",
    EXTERNAL_CALENDAR_SYNC_TRIGGER_URL: "/api/sync-mac-calendar",
    EXTERNAL_CALENDAR_PUSH_URL: "/api/push-mac-calendar-event",
    EXTERNAL_CALENDAR_LIST_URL: "/api/calendars/list",
    EXTERNAL_REMINDER_LIST_URL: "/api/reminders/lists",
    EXTERNAL_TASK_SYNC_URL: "/api/tasks/sync-to-mac-calendar",
    EXTERNAL_TASK_DELETE_URL: "/api/tasks/delete-from-mac-calendar",
    EXTERNAL_TASK_PULL_URL: "/api/tasks/pull-from-mac-calendar",
    EXTERNAL_TASK_REMINDER_SYNC_URL: "/api/tasks/sync-to-mac-reminders",
    EXTERNAL_TASK_REMINDER_COMPLETE_URL: "/api/tasks/complete-in-mac-reminders",
    INTERNAL_UPDATE_STATUS_URL: "/api/internal-update/status",
    INTERNAL_UPDATE_CHECK_URL: "/api/internal-update/check",
    INTERNAL_UPDATE_APPLY_URL: "/api/internal-update/apply",
    INTERNAL_UPDATE_FORCE_APPLY_URL: "/api/internal-update/force-apply",
    INTERNAL_UPDATE_BACKUPS_URL: "/api/internal-update/backups",
    INTERNAL_UPDATE_BACKUP_RESTORE_URL: "/api/internal-update/backups/restore",
    RUNTIME_CONFIG_URL: "/api/runtime/config",
    LOCAL_DATA_BACKUP_URL: "/api/local-data/backup",
    LOCAL_DATA_LATEST_URL: "/api/local-data/latest",
    LOCAL_DATA_SNAPSHOTS_URL: "/api/local-data/snapshots",
    LOCAL_DATA_RESTORE_URL: "/api/local-data/restore",
    INSTALL_GUIDE_DISMISSED_KEY: "time_quality_install_guide_dismissed_v1",
    EXTERNAL_CALENDAR_SOURCE: "mac-calendar",
    EXTERNAL_CALENDAR_IGNORED_KEY: "time_quality_calendar_ignored_v1",
    TODO_STORAGE_KEY: "time_quality_todos_v1",
    TODO_DELETE_QUEUE_STORAGE_KEY: "time_quality_todo_delete_queue_v1",
    TODO_REMINDER_DISABLE_QUEUE_STORAGE_KEY: "time_quality_todo_reminder_disable_queue_v1",
    TODO_REMINDER_DEFAULT_LEAD_STORAGE_KEY: "time_quality_todo_reminder_default_lead_v1",
    SIDEBAR_WIDTH_STORAGE_KEY: "time_quality_sidebar_width_v1",
    SIDEBAR_COLLAPSED_STORAGE_KEY: "time_quality_sidebar_collapsed_v1",
    TODO_DETAIL_WIDTH_STORAGE_KEY: "time_quality_todo_detail_width_v1",
    POMODORO_FLOAT_LAYOUT_STORAGE_KEY: "time_quality_pomodoro_float_layout_v1",
    SIDEBAR_TAXONOMY_RANGE_STORAGE_KEY: "time_quality_sidebar_taxonomy_range_v1",
    SIDEBAR_PROJECT_COLLAPSE_STORAGE_KEY: "time_quality_sidebar_project_collapsed_v1",
    TODO_PROJECT_TREE_COLLAPSE_STORAGE_KEY: "time_quality_todo_project_collapsed_v1",
    CATEGORY_STORAGE_KEY: "time_quality_categories_v1",
    SYNC_CALENDAR_TARGET_STORAGE_KEY: "time_quality_sync_calendar_target_v1",
    SYNC_CALENDAR_TARGET_CONFIRMED_KEY: "time_quality_sync_calendar_target_confirmed_v2",
    SYNC_REMINDER_TARGET_STORAGE_KEY: "time_quality_sync_reminder_target_v1",
    CALENDAR_SAMPLE_16_SEEDED_KEY: "time_quality_calendar_sample_16_seeded_v2",
    CACHE_RESET_ONCE_KEY: "time_quality_cache_reset_once_v2",
    EXTERNAL_CALENDAR_DEFAULT_CATEGORY: "工作",
    EXTERNAL_CALENDAR_AUTO_TODO_ENABLED: true,
    EXTERNAL_CALENDAR_AUTO_TODO_MAX_DURATION_HOURS: 12,
    DEFAULT_SYNC_TARGET_SOURCE_NAME,
    DEFAULT_SYNC_TARGET_CALENDAR_NAME,
    DEFAULT_SYNC_TARGET_GROUP: `${DEFAULT_SYNC_TARGET_SOURCE_NAME}/${DEFAULT_SYNC_TARGET_CALENDAR_NAME}`,
    DEFAULT_REMINDER_TARGET_SOURCE_NAME,
    DEFAULT_REMINDER_TARGET_LIST_NAME,
    DEFAULT_REMINDER_TARGET_GROUP: `${DEFAULT_REMINDER_TARGET_SOURCE_NAME}/${DEFAULT_REMINDER_TARGET_LIST_NAME}`,
    TODO_REMINDER_DEFAULT_LEAD_MINUTES: 0,
    TODO_REMINDER_DEFAULT_LEAD_OPTIONS: [0, 5, 10],
    DEFAULT_SCORE: 7,
    DEFAULT_POMODORO_MINUTES: 25,
    SCATTER_PADDING_PERCENT: 6,
    HARD_SNAP_GUTTER: 28,
    SCATTER_BASE_DURATION_HOURS: 0.5,
    SCATTER_BASE_DIAMETER: 12,
    SCATTER_MIN_DIAMETER: 8,
    SCATTER_MAX_DIAMETER: 28,
    POMODORO_DIAL_START_DEG: -90,
    POMODORO_DIAL_RUNNING_CLASS: "is-running",
    CALENDAR_DEFAULT_CENTER_HOUR: 12,
    CALENDAR_DEFAULT_HIDE_BEFORE_HOUR: 8,
    CALENDAR_CLICK_MINUTE_STEP: 15,
    CALENDAR_NEW_EVENT_DEFAULT_DURATION_MINUTES: 60,
    CALENDAR_DIRECT_EDIT_MINUTES_STEP: 15,
    CALENDAR_DIRECT_EDIT_MIN_DURATION_MINUTES: 15,
    CALENDAR_DIRECT_EDIT_DRAG_SLOP_PX: 4,
    CALENDAR_DIRECT_EDIT_CLICK_SUPPRESS_MS: 260,
    CALENDAR_NOW_LINE_REFRESH_MS: 30000,
    TODO_PLAN_ENTRY_ID_PREFIX: "todo-plan:",
    TODO_PLAN_DAY_FIRST_START_MINUTES: 9 * 60 + 30,
    TODO_PLAN_DAY_FIRST_DURATION_MINUTES: 45,
    TODO_PLAN_DAY_NEXT_DURATION_MINUTES: 5,
    TODO_PLAN_NEW_TODO_DURATION_MINUTES: 45,
    TODO_PLAN_DAY_GAP_MINUTES: 5,
    TODO_COMPLETION_KEEP_VISIBLE_MS: 5000,
    TODO_NOTE_HELPER_TEXT: "补充你的执行要点。",
    TODO_PROJECT_MAX_LEVEL: 3,
    TODO_PROJECT_LEVEL_SEPARATOR: " / ",
    GLOBAL_SEARCH_RESULT_LIMIT: 12,
    GLOBAL_SEARCH_TARGET_HIGHLIGHT_MS: 1400,
    AUTO_BIDIRECTIONAL_SYNC_ENABLED: true,
    AUTO_BIDIRECTIONAL_SYNC_DEBOUNCE_MS: 1800,
    AUTO_BIDIRECTIONAL_SYNC_PULL_INTERVAL_MS: 60000,
    AUTO_BIDIRECTIONAL_SYNC_START_DELAY_MS: 2500,
    SIDEBAR_MIN_WIDTH: 220,
    SIDEBAR_MAX_WIDTH: 420,
    TODO_DETAIL_MIN_WIDTH: 320,
    TODO_DETAIL_MAX_WIDTH: 640,
    TODO_LIST_MIN_WIDTH: 420,
    UNDO_HISTORY_LIMIT: 60,
    UNDO_MERGE_WINDOW_MS: 320,
    SCORE_INPUT_WHEEL_PIXEL_THRESHOLD: 60,
    SCORE_INPUT_WHEEL_LINE_THRESHOLD: 3,
    SCORE_INPUT_WHEEL_RESET_MS: 220,
    SCORE_WHEEL_ITEM_SPACING_PX: 25.5,
    SCORE_WHEEL_DRAG_STEP_PX: 12,
    SCORE_WHEEL_SCROLL_THRESHOLD_PX: 14,
    SCORE_WHEEL_ITEM_VISIBLE_RADIUS: 3,
    SCORE_WHEEL_INERTIA_MIN_VELOCITY: 0.045,
    SCORE_WHEEL_INERTIA_FRICTION_PER_FRAME: 0.9,
    SCORE_WHEEL_INERTIA_MAX_DT_MS: 34,
    SCORE_WHEEL_MAX_BOUNCES: 1,
    SCORE_WHEEL_BOUNCE_CLASS_HOLD_MS: 190,
    CALENDAR_SAMPLE_16_MARKER: "[样例16]",
    DATA_EXPORT_SCHEMA: "timequality-local-storage-export-v1",
    DATA_EXPORT_STORAGE_PREFIX: "time_quality_",
  };

  globalScope.TimeQualityConfig = Object.freeze({
    ...config,
    TODO_REMINDER_DEFAULT_LEAD_OPTIONS: Object.freeze([...config.TODO_REMINDER_DEFAULT_LEAD_OPTIONS]),
  });
})(typeof window !== "undefined" ? window : globalThis);
